remote_theme: coursweb/jk-theme
title: Infos IMD
description: Informations pour enseignant-es IMD.
lang: fr-FR
# markdown: GFM
robots: noindex, nofollow
chapters:
 - title: Infos IMD
   url: https://code.eracom-pedagogique.ch/infos-profs-imd/
 - title: PÃ©dagogie
   url: https://code.eracom-pedagogique.ch/pedagogie/
 - title: Livres
   url: https://code.eracom-pedagogique.ch/livres-imd/
 - title: Fontes
   url: https://code.eracom-pedagogique.ch/fontes-imd/  
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom/infos-profs-imd">Lien Github</a></li></ul>
footer_col_3: Informations pour enseignant-es IMD.